# Generated by Django 5.0.6 on 2026-05-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], db_index=True, default='PENDING', max_length=20)),
                ('total_wh', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('main', models.IntegerField(default=1)),
                ('mqtt_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to='myapp.device')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='myapp.worker_details')),
            ],
            options={
                'unique_together': {('device', 'cycle_number')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('voltage_r', models.FloatField()),
                ('voltage_y', models.FloatField()),
                ('voltage_b', models.FloatField()),
                ('current_r', models.FloatField()),
                ('current_y', models.FloatField()),
                ('current_b', models.FloatField()),
                ('wh', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='power_monitoring.monitoringsession')),
            ],
        ),
    ]
