# Generated by Django 5.0.6 on 2026-04-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsession',
            name='mqtt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
