"""
Django settings for water project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# # import dotenv
# from dotenv import load_dotenv
# import os
# load_dotenv()    

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zxw+xuj_v)b0$akg0gkx7hmxw$10dj4ei4vt*@ym-(i3mb)p)y'


# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
ALLOWED_HOSTS = ['*','masterbg.bc-pl.com'] 

  

# Application definition
INSTALLED_APPS = [   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'corsheaders',
    'googlemaps',
    'mobile_app',
    'myapp',
    'geoposition',
    'rest_framework',
    'rest_framework.authtoken',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'water.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'water.wsgi.application'
# ASGI_APPLICATION = 'water.asgi.application'


# ############################# DATABASE ######################
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {  
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "aquafarm",  
        "USER": "Vertoxlabs1987Bfl",         
        "PASSWORD": "Vtx@1987#2026#Bfl@", 
        "HOST": 'vertoxlabsdb.postgres.database.azure.com',
        "PORT": "5432",
        'OPTIONS': {
            'sslmode': 'require',  
        },
    }}
###################################################################


TWOFACTOR_API_KEY = '77455b09-e5df-11ee-8cbb-0200cd936042'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

###########################common login database ##########################
COMMONLOGIN_DB_NAME = 'commonlogin'
COMMONLOGIN_DB_USER = "Vertoxlabs1987Bfl"
COMMONLOGIN_DB_PASS = "Vtx@1987#2026#Bfl@"
COMMONLOGIN_DB_HOST = 'vertoxlabsdb.postgres.database.azure.com'
COMMONLOGIN_DB_PORT = '5432'
############################################################################


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'dist'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CSRF_TRUSTED_ORIGINS = [
    'https://masterbg.bc-pl.com',
    'http://20.6.11.71:3000',
]
#CORS_ALLOWED_ORIGINS = [
   # 'https://master.bc-pl.com',
  #  "http://localhost:3001",
 #   "http://localhost:3000",
#]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

########################## Email configuration ##############
EMAIL_BACKEND= "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'care.bariflolabs@gmail.com ' 
EMAIL_HOST_PASSWORD = 'pgvw cgtd hkbh chak' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
#############################################################
8000
# import razorpay
# RAZORPAY_KEY_ID = 'rzp_test_M4wPEnBM4t1hog'
# RAZORPAY_KEY_SECRET = 'P4GVB18vIsqzqKF47bYaEf9k'


########## Redis configuration (LOCAL / LAN) ################
REDIS_HOST = "192.168.1.40"
REDIS_PORT = 6379          # default local Redis port
REDIS_PASSWORD = "master"
REDIS_DB = 0
REDIS_SSL = False
##############################################################

############### Session engine configuration #################
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

################ Telegram Token configuration ################
TOKEN = '8359846344:AAG_LPrbj0weS27hUeUF8Fi1Zxcl9W-kFSU'

###################### Image Configurations ##################

MEDIA_URL = '/media/'
MEDIA_ROOT ="/home/bariflo/Desktop"
