"""
Django settings for water project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# import dotenv
# from dotenv import load_dotenv
# import os
# load_dotenv()
from glob import glob
from dotenv import load_dotenv    

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

_env_path = os.path.join(BASE_DIR, ".env")
try:
    load_dotenv(_env_path, encoding="utf-8-sig")
except TypeError:
    load_dotenv(_env_path)

### For Check Tray Telegram
AZURE_COMMUNICATION_CONNECTION_STRING = os.getenv("AZURE_COMMUNICATION_CONNECTION_STRING")
TELEGRAM_BOT_TOKEN = (os.getenv("TELEGRAM_BOT_TOKEN") or "").strip() or None
_raw_chat = os.getenv("TELEGRAM_GROUP_CHAT_ID")
TELEGRAM_GROUP_CHAT_ID = (_raw_chat.strip() if _raw_chat else None) or None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zxw+xuj_v)b0$akg0gkx7hmxw$10dj4ei4vt*@ym-(i3mb)p)y'


# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
ALLOWED_HOSTS = ['*','masterbg.bc-pl.com'] 

  

# Application definition
INSTALLED_APPS = [   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'corsheaders',
    'googlemaps',
    'mobile_app',
    'myapp',
    'geoposition',
    'rest_framework',
    'rest_framework.authtoken',
    'checktray.apps.ChecktrayConfig',
    'power_monitoring',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'water.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'water.wsgi.application'
# ASGI_APPLICATION = 'water.asgi.application'


# ############################# DATABASE ######################

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "aquafarm",
        "USER": "Vertoxlabs1987Bfl",
        "PASSWORD": "Vtx@1987#2026#Bfl@",
        "HOST": "vertoxlabsdb.postgres.database.azure.com",
        "PORT": "5432",
        "CONN_MAX_AGE": 60,
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}

###################################################################


TWOFACTOR_API_KEY = '77455b09-e5df-11ee-8cbb-0200cd936042'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = False

###########################common login database ##########################
COMMONLOGIN_DB_NAME = 'commonlogin'
COMMONLOGIN_DB_USER = "Vertoxlabs1987Bfl"
COMMONLOGIN_DB_PASS = "Vtx@1987#2026#Bfl@"
COMMONLOGIN_DB_HOST = 'vertoxlabsdb.postgres.database.azure.com'
COMMONLOGIN_DB_PORT = '5432'
############################################################################


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'dist'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CSRF_TRUSTED_ORIGINS = [
    'https://masterbg.bc-pl.com',
    'http://20.6.11.71:3000',
]
#CORS_ALLOWED_ORIGINS = [
   # 'https://master.bc-pl.com',
  #  "http://localhost:3001",
 #   "http://localhost:3000",
#]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

########################## Email configuration ##############
EMAIL_BACKEND= "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'care.bariflolabs@gmail.com ' 
EMAIL_HOST_PASSWORD = 'pgvw cgtd hkbh chak' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
#############################################################
# import razorpay
# RAZORPAY_KEY_ID = 'rzp_test_M4wPEnBM4t1hog'
# RAZORPAY_KEY_SECRET = 'P4GVB18vIsqzqKF47bYaEf9k'


########## Redis configuration (LOCAL / LAN) ################
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
##############################################################

############### Session engine configuration #################
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


###################### Image Configurations ##################

MEDIA_URL = '/media/'
MEDIA_ROOT ="/home/bariflo/Desktop"


AZURE_STORAGE_ACCOUNT_NAME="vertoxlabblob1"
AZURE_STORAGE_CONTAINER="vertoxdb"
AZURE_STORAGE_ACCOUNT_KEY="aYOMbNdrpbzGqmCNkwHFGmcmRw+s0bRskVcy3nDjLsG7fle1zyWyY39YG1dKcGEuTHL+yldRdpty+AStdh1wsg=="


CELERY_BROKER_URL = 'redis://127.0.0.1:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'
CELERY_TIMEZONE = 'Asia/Kolkata'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'start-scheduled-cycles-every-1-min': {
        'task': 'myapp.tasks.start_scheduled_cycles',
        'schedule': 60.0,  # every 60 seconds
    },
}