# Generated by Django 5.0.6 on 2025-12-29 05:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('maxCycles', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('user_category', models.CharField(choices=[('3d', '3d'), ('analytics', 'analytics'), ('aqua', 'aqua'), ('water', 'water')], default=(('3d', '3d'), ('analytics', 'analytics'), ('aqua', 'aqua'), ('water', 'water')), max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('photo_file_id', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_type', models.CharField(choices=[('truck', 'Truck'), ('received_chalan', 'Received Chalan'), ('chalan', 'Chalan'), ('shrimp_boxes', 'Shrimp Boxes')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Mob', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('avtar', models.ImageField(default='avtar/avtar.png', upload_to='avtar/')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Company_name', models.CharField(max_length=30, unique=True)),
                ('Mob', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('Pan_no', models.CharField(max_length=50)),
                ('GST_no', models.CharField(max_length=50)),
                ('user_category', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CycleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(auto_now=True)),
                ('cycles', models.CharField(max_length=2)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle', to='myapp.device')),
            ],
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('latlong', models.CharField(max_length=150)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('telegram_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('device_quantity', models.JSONField(default=dict)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='myapp.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.FloatField(blank=True, null=True)),
                ('dissolved_oxygen', models.FloatField(blank=True, null=True)),
                ('NDVI', models.FloatField(blank=True, null=True)),
                ('NDTI', models.FloatField(blank=True, null=True)),
                ('GCI', models.FloatField(blank=True, null=True)),
                ('NDCI', models.FloatField(blank=True, null=True)),
                ('NDWI', models.FloatField(blank=True, null=True)),
                ('TSS', models.FloatField(blank=True, null=True)),
                ('CDOM', models.FloatField(blank=True, null=True)),
                ('AQUATIC_MACROPYTES', models.FloatField(blank=True, null=True)),
                ('Phycocyanin', models.FloatField(blank=True, null=True)),
                ('Chl_a', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pond')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='pond_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='myapp.pond'),
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('service_name', models.CharField(max_length=50, null=True, verbose_name='Service Name')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Id')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pond_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pond')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('Mob', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('user_category', models.CharField(choices=[('Aquafarming', 'Aquafarming'), ('WaterBody', 'WaterBody')], max_length=50)),
                ('token', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Worker_details',
            fields=[
                ('mobno', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.manager')),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
