# Generated by Django 5.0.6 on 2025-12-29 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.CharField(max_length=10)),
                ('to_time', models.CharField(max_length=10)),
                ('feed_weight', models.FloatField(blank=True, null=True)),
                ('probiotic', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
                ('taskcatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task_category')),
                ('worker_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.worker_details')),
            ],
        ),
    ]
