# Generated by Django 5.0.6 on 2026-05-05 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_details',
            name='user',
        ),
        migrations.AddField(
            model_name='pond',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.manager'),
        ),
        migrations.AddField(
            model_name='worker_details',
            name='pond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pond'),
        ),
    ]
