# Generated by Django 5.0.6 on 2026-05-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
