# Generated by Django 5.0.6 on 2025-12-29 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('message_id', models.BigIntegerField()),
                ('time_poll_id', models.BigIntegerField()),
                ('size_poll_id', models.BigIntegerField(blank=True, null=True)),
                ('color_poll_id', models.BigIntegerField(blank=True, null=True)),
                ('dieses_poll_id', models.BigIntegerField(blank=True, null=True)),
                ('moulting_poll_id', models.BigIntegerField(blank=True, null=True)),
                ('shrimp_size', models.CharField(blank=True, max_length=50, null=True)),
                ('shrimp_color', models.CharField(blank=True, max_length=50, null=True)),
                ('diesese', models.CharField(blank=True, max_length=50, null=True)),
                ('moulting', models.CharField(blank=True, max_length=50, null=True)),
                ('pond_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pond')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
        ),
    ]
