# Generated by Django 5.0.6 on 2026-05-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_category',
            field=models.CharField(choices=[('Aquafarming', 'Aquafarming'), ('WaterBody', 'WaterBody')], default='Aquafarming', max_length=50),
        ),
    ]
