# Generated by Django 5.0.6 on 2026-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_worker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=100),
        ),
    ]
