# Generated by Django 5.0.6 on 2025-12-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cycles',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
