# Generated by Django 5.0.6 on 2025-12-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cycles',
            field=models.CharField(max_length=20),
        ),
    ]
