# Generated by Django 5.0.6 on 2026-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_manager_password_alter_manager_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='maxCycles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
