# Generated by Django 5.0.6 on 2025-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_task_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('nill', 'Nill'), ('processing', 'Processing'), ('completed', 'Completed'), ('abort', 'Abort')], default='nill', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='cycles',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='to_time',
            field=models.TimeField(),
        ),
    ]
