# Generated by Django 5.0.6 on 2025-12-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task_status_alter_task_created_at_alter_task_cycles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
