# Generated by Django 5.0.6 on 2025-12-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_task_from_time_alter_task_to_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
