# Generated by Django 5.0.6 on 2025-12-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='probiotic',
            new_name='spray_type',
        ),
    ]
