# Generated by Django 5.0.6 on 2025-12-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_task_depth_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='time_interval',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
