# Generated by Django 5.0.6 on 2025-12-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_task_date_task_time_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
    ]
