# Generated by Django 5.0.6 on 2025-12-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
