# Generated by Django 5.0.6 on 2025-12-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_task_feedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='feed_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
