# Generated by Django 5.0.6 on 2025-12-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_task_feed_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedin_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
