# Generated by Django 5.0.6 on 2025-12-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_task_feedin_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cycles',
            field=models.CharField(max_length=5),
        ),
    ]
