# Generated by Django 5.0.6 on 2025-12-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_task_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cycles',
            field=models.IntegerField(max_length=5),
        ),
    ]
