# Generated by Django 5.0.6 on 2026-01-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_task_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('abort', 'Abort')], default='processing', max_length=20),
        ),
    ]
