# Generated by Django 5.0.6 on 2026-01-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_devicecommandstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_feed_rate',
            field=models.CharField(default=100, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_sprinkle_rate',
            field=models.CharField(default=4000, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='restfeed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
