# Generated by Django 5.0.6 on 2026-01-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_task_auto_feed_rate_task_auto_sprinkle_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_door',
            field=models.IntegerField(default=1000),
        ),
    ]
