# Generated by Django 5.0.6 on 2026-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_alert_message_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_message',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
