# Generated by Django 5.0.6 on 2026-01-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_alert_message_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommandstate',
            name='device_id',
            field=models.CharField(max_length=50),
        ),
    ]
