# Generated by Django 5.0.6 on 2026-01-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_devicecommandstate_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommandstate',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
