# Generated by Django 5.0.6 on 2026-01-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_devicecommandstate_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommandstate',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert_message',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
