# Generated by Django 5.0.6 on 2026-01-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_devicecommandstate_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='feed_weight',
        ),
        migrations.RemoveField(
            model_name='task',
            name='feedin_percentage',
        ),
        migrations.AlterField(
            model_name='task',
            name='auto_door',
            field=models.IntegerField(default=3750),
        ),
    ]
