# Generated by Django 5.0.6 on 2026-01-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_task_feed_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feed_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='feedin_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
