# Generated by Django 5.0.6 on 2026-01-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_task_feed_weight_task_feedin_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommandstate',
            name='timepergm',
            field=models.DecimalField(decimal_places=5, default=0.00125, max_digits=10),
        ),
    ]
