# Generated by Django 5.0.6 on 2026-01-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_devicecommandstate_timepergm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_interval',
            field=models.CharField(blank=True, null=True),
        ),
    ]
