# Generated by Django 5.0.6 on 2026-01-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_task_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='feedin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='restfeed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
