# Generated by Django 5.0.6 on 2026-02-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_task_feedin_alter_task_restfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('abort', 'Abort'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
