# Generated by Django 5.0.6 on 2026-02-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='myapp.user'),
        ),
    ]
