# Generated by Django 5.0.6 on 2026-03-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_cluster_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='spray_type',
        ),
    ]
