# Generated by Django 5.0.6 on 2026-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_task_depth_remove_task_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='spray_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
