# Generated by Django 5.0.6 on 2026-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_task_depth_task_image_task_quantity_task_spray_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('abort', 'Abort'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
