# Generated by Django 5.0.6 on 2026-04-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_task_is_published_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='extra_feed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
