# Generated by Django 5.0.6 on 2026-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_task_extra_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='auto_door',
            field=models.IntegerField(default=3000),
        ),
    ]
