# Generated by Django 5.0.6 on 2026-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_task_auto_door'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='auto_sprinkle_rate',
            field=models.CharField(default=1000, max_length=255),
        ),
    ]
