# Generated by Django 5.0.6 on 2026-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_task_auto_sprinkle_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
