# Generated by Django 5.0.6 on 2026-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_task_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cycles',
            field=models.IntegerField(),
        ),
    ]
