# Generated by Django 5.0.6 on 2026-04-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_task_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
