# Generated by Django 5.0.6 on 2026-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_task_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('unknown State', 'Unknown State')], default='pending', max_length=20),
        ),
    ]
