# Generated by Django 5.0.6 on 2026-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0047_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="worker_call_notified",
            field=models.BooleanField(default=False),
        ),
    ]
