# Generated by Django 5.0.6 on 2026-02-28 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0037_alter_cluster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecktrayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.IntegerField()),
                ('sparay_cycle', models.CharField(blank=True, max_length=4, null=True, verbose_name=('YES', 'YES', 'No', 'No'))),
                ('image_update', models.CharField(blank=True, max_length=4, null=True, verbose_name=('YES', 'YES', 'No', 'No'))),
                ('water_level', models.FloatField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('complete_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
            ],
        ),
    ]
