# Generated by Django 5.0.6 on 2026-03-03 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=30)),
                ('image_type', models.CharField(choices=[('color', 'Color'), ('thermal', 'Thermal')], max_length=20)),
                ('storage_mode', models.CharField(choices=[('azure', 'Azure'), ('local', 'Local')], max_length=10)),
                ('logical_path', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
