# Generated by Django 5.0.6 on 2026-05-05 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=30)),
                ('image_type', models.CharField(choices=[('color', 'Color'), ('thermal', 'Thermal')], max_length=20)),
                ('storage_mode', models.CharField(choices=[('azure', 'Azure'), ('local', 'Local')], max_length=10)),
                ('logical_path', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChecktrayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spray_cycle', models.CharField(blank=True, choices=[('YES', 'YES'), ('No', 'No')], max_length=4, null=True)),
                ('image_update', models.CharField(blank=True, choices=[('YES', 'YES'), ('No', 'No')], max_length=4, null=True)),
                ('water_level', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('submit', models.CharField(default='False', max_length=10)),
                ('notified', models.BooleanField(default=False)),
                ('worker_call_notified', models.BooleanField(default=False)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
                ('worker_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.worker_details')),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'status'], name='checktray_c_device__aae8db_idx'), models.Index(fields=['status'], name='checktray_c_status_65822d_idx'), models.Index(fields=['start_time'], name='checktray_c_start_t_21945f_idx')],
            },
        ),
    ]
