# Generated by Django 5.0.6 on 2026-03-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checktray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktraytask',
            name='submit',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
