# Generated by Django 5.0.6 on 2026-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checktray', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktraytask',
            name='worker_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
