# Generated by Django 5.0.6 on 2026-03-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checktray', '0001_initial'),
        ('myapp', '0037_alter_cluster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecktrayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.IntegerField()),
                ('sparay_cycle', models.CharField(blank=True, choices=[('YES', 'YES'), ('No', 'No')], max_length=4, null=True)),
                ('image_update', models.CharField(blank=True, choices=[('YES', 'YES'), ('No', 'No')], max_length=4, null=True)),
                ('water_level', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'status'], name='checktray_c_device__aae8db_idx'), models.Index(fields=['status'], name='checktray_c_status_65822d_idx'), models.Index(fields=['start_time'], name='checktray_c_start_t_21945f_idx')],
            },
        ),
    ]
