# Generated by Django 5.0.6 on 2026-04-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checktray', '0002_checktraytask_submit'),
        ('myapp', '0039_task_depth_task_image_task_quantity_task_spray_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktraytask',
            name='worker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.worker_details'),
        ),
    ]
