# Generated by Django 5.0.6 on 2026-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checktray', '0003_checktraytask_worker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktraytask',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
