# Generated by Django 5.0.6 on 2026-04-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checktray", "0004_checktraytask_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="checktraytask",
            name="worker_call_notified",
            field=models.BooleanField(default=False),
        ),
    ]
